apartments = [
  {
    "id": 0,
    "url": "https://www.zillow.com/apartments/dublin-oh/gorden-farms/Ckh4fC/",
    "name": "Gordon Farms",
    "price": 1650,
    "address": "7200 Gorden Farms Pkwy, Dublin, OH 43016",
    "latitude": 40.110219,
    "longitude": -83.169342,
    "beds": 2,
    "baths": 2,
    "lot_size_sqft": 1122,
    "description": "Gorden Farms is located in prestigious Dublin, Ohio. Here, you'll find luxury living at it's finest. Our community features six beautiful one and two bedroom garden and two bedroom town home style floor plans. Features include open floor plans, washer/dryer connections, patios and balconies, and fireplaces in select units. Gorden Farms is located just minutes from a multitude of dining, shopping, and entertainment venues. We offer wonderful amenities including a sparkling swimming pool, on-site fitness center, ample parking, and garages! With convenient access to 161 and 270, you won't want to miss out on this gorgeous community. Stop in today to find your new home!",
    "listing_agent":"Spring Property Management",
    "contact": "(380) 205-3698",
    "amenities": ["Club House","Fitness Center","Laundry: Hookups","Swimming Pool"],
    "lease_terms": ["Flexible","One year"],
    "images": []
  },
  {
    "id": 1,
    "url": "https://www.zillow.com/homedetails/5252-Willow-Grove-Pl-S-Dublin-OH-43017/34064106_zpid/",
    "name": "Willow Grove Condominiums",
    "price": 2450,
    "address": "5252 Willow Grove Pl S, Dublin, OH 43017",
    "latitude": 40.1165,
    "longitude": -83.1398,
    "beds": 3,
    "baths": 2.5,
    "lot_size_sqft": 1620,
    "description": "Willow Grove Condominiums on the corner of Emerald Pkwy and Post Road; 3 bedrooms; 2 full bathrooms and 1 half bath; unfinished basement; attached one-car garage with driveway space for another car; off-street parking spots nearby; gated, key entry community pool just steps from your fenced-in back patio. Quiet community across the street from Coffman Park, home of the annual Dublin Irish Festival. Dublin schools, Coffman High School district; contact Dublin Schools Administration for most current districting, but it is believed to be Bailey Elementary, Grizzell Middle and Coffman High School at this time. Just minutes to I-270 and all that Dublin, Bridge Park and Columbus have to offer. One pet allowed with payment of $500.00 refundable pet deposit.",
    "listing_agent":"Jay Eggspuehler",
    "contact": "(614) 214-7250",
    "amentities": ["Washer/Dryer hookup (WD Hookup)","Attached garage","Community pool","Fenced‑in back patio"],
    "lease_terms": ["1 Year"], 
    "images": []
  },

  {
    "id": 2,
    "url": "https://www.zillow.com/homedetails/1501-1507-Michigan-Ave-Columbus-OH-43201/33939076_zpid/",
    "name": "Michigan Ave, Columbus, OH",
    "price": 2445,
    "address": "1501-1507 Michigan Ave, Columbus, OH 43201",
    "latitude": 39.991875,
    "longitude": -83.016555,
    "beds": 4,
    "baths": 1.5,
    "lot_size_sqft": 1746,
    "description": "4 Bd 1.5 Ba one side of a duplex next to OSU medical campus. Fully renovated with a brand new kitchen with granite counter, white cabinets and SS appliances. Brand new windows with blinds, and new 1.5 baths (first floor half bath). Spacious living and dining rooms with bar area, original pocket doors, original wood works and decorative fireplace. Upstairs feature the updated full bath with floor to ceiling tiled shower and three sizeable bedrooms with ample closet spaces (decorative fireplace in one room), bright tall windows as well as ceiling fan lights in each bedroom. There is an additional third level finished as two study/office/guest rooms. Rent include basement washer/dryer and off street parkings and lawn care (no snow removal). Utilities are on tenants and refundable pet deposit and monthly rent apply.",
    "listing_agent": "7rent com",
    "contact": "(614) 725-5777",
    "amentities": ["Dishwasher, Dryer, Freezer, Microwave, Oven, Refridgerator, Washer"],
    "lease_terms": ["1 Year", "Pets Allowed"], 
    "images": []
  },

  {
    "id": 3,
    "url": "https://www.zillow.com/homedetails/1537-Doten-Ave-Columbus-OH-43212/2090723976_zpid/",
    "name": "Michigan Ave, Columbus, OH",
    "price": 2445,
    "address": "1537 Doten Ave, Columbus, OH 43212",
    "latitude": 39.990104,
    "longitude": -83.037938,
    "beds": 1,
    "baths": 1,
    "lot_size_sqft": 1746,
    "description": "Beautiful apartment with hardwood floors, updated tile bathroom, washer/dryer, lots of storage and green space . Located in the Grandview area and very walkable to everything you need.",
    "listing_agent":"Dan Bryan",
    "contact": "(380) 205-2349",
    "amentities": ["Dryer, Washer, Laundry: In Unit", "Flooring: Hardwoord", "Cooling: Central air"],
    "lease_terms": ["1 Year", "Pets Allowed"], 
    "images": []
  }
]